catalogs:
  eslint:
    "@eslint/js": ^9.39.0
    "@next/eslint-plugin-next": ^16.0.1
    eslint: ^9.39.0
    eslint-config-prettier: ^10.1.8
    eslint-plugin-only-warn: ^1.1.0
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^5.2.0 # 7.0.1?
    eslint-plugin-turbo: ^2.6.0
    globals: ^16.5.0
    typescript-eslint: ^8.46.2
  next16:
    next: ^16.0.1
  node24:
    "@types/node": ^24.9.2
  prettier:
    prettier: ^3.6.2
  react19:
    "@types/react": ^19.2.2
    "@types/react-dom": ^19.2.2
    react: ^19.2.0
    react-dom: ^19.2.0
  typescript5:
    typescript: ^5.9.3

packages:
  - "apps/*"
  - "packages/*"
